# Generated by Django 3.2.9 on 2021-11-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
